---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
    driver:
      network:
        - ["forwarded_port", {guest: 8081, host: 8081}]
        - ["forwarded_port", {guest: 8443, host: 8443}]
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: "test/integration/default/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/default/data_bags/encrypted_data_bag_secret"
    run_list:
      - recipe[nexus::default]
    attributes:
      nexus:
        cli:
          ssl:
            verify: "false"
        app_server_proxy:
          use_self_signed: "true"
